apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.properties: |
    # Application configuration properties
    # Example properties
    server.port=8080
    spring.datasource.url=jdbc:mysql://localhost:3306/mydb
    spring.datasource.username=user
    spring.datasource.password=pass
    logging.level.root=INFO
    logging.level.com.example=DEBUG