apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-k8s-app
  labels:
    app: java-k8s-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-k8s-app
  template:
    metadata:
      labels:
        app: java-k8s-app
    spec:
      containers:
      - name: java-k8s-app
        image: your-docker-repo/java-k8s-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      imagePullSecrets:
      - name: regcred